### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by why228430** [xuguodong03/SSKD#3]
BrokenPipeError：[Errno 32] Broken pipe
when I run the teacher.py by python teacher.py --arch wrn_40_2 --lr 0.05 --gpu-id 0. I miss the error,What can I do to solve this problem？ @xuguodong03

**Comment by xuguodong03** [comment]
Can you provide the whole error information printed in console?

**Comment by why228430** [comment]
(base) C:\Users\11619\Desktop\SSKD-master>python teacher.py --arch wrn_40_2 --lr 0.05 --gpu-id 0
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\11619\Desktop\SSKD-master\teacher.py", line 78, in <module>
    for x, (target, _) in enumerate(train_loader):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
Traceback (most recent call last):
  File "teacher.py", line 78, in <module>
    for x, (target, _) in enumerate(train_loader):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    return _MultiProcessingDataLoaderIter(self)
      File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
w.start()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 112, in start
    w.start()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
      File "D:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
return Popen(process_obj)  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__

  File "D:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by xuguodong03** [comment]
I notice that you are using Windows platform.The error is related to the multithreading of Dataloader on Windows. For more details, see this [issue](https://github.com/pytorch/pytorch/issues/2341). You could try setting num_workers=0. But this will slow down the speed of data loading. I recommend to run the code on Ubuntu platform.

**Comment by why228430** [comment]
Thanks for you reply. My problem is solved. I will accept your recommend  to run the code on Ubuntu platform.
